package com.chorus.engine.agent.selfhealing;

import com.chorus.engine.agent.middleware.Middleware;
import com.chorus.engine.core.context.Message;
import com.chorus.engine.core.context.TokenCount;
import com.chorus.engine.core.result.Result;
import com.chorus.engine.llm.ToolDefinition;
import org.jspecify.annotations.NonNull;

import java.time.Duration;
import java.util.List;
import java.util.Map;

/**
 * Middleware injected by {@link SelfHealingAgentLoop} at the front of the
 * middleware chain (priority {@link Integer#MIN_VALUE}) to apply heal actions
 * generated by the policy.
 *
 * <ul>
 *   <li>{@link #beforeRound} — blocks for the pending backoff delay (consumed once).</li>
 *   <li>{@link #extraSystemPrompt} — injects the heal instruction into every subsequent
 *       round until a new heal decision overwrites it.</li>
 * </ul>
 */
final class HealingMiddleware implements Middleware {

    private final HealingState state;

    HealingMiddleware(@NonNull HealingState state) {
        this.state = state;
    }

    @Override
    public int priority() { return Integer.MIN_VALUE; }

    @Override
    public @NonNull Result<String, MiddlewareError> beforeRound(
            @NonNull String runId,
            @NonNull List<Message> history,
            @NonNull Map<String, Object> context) {
        Duration backoff = state.takeBackoff();
        if (backoff != null && !backoff.isZero()) {
            try {
                Thread.sleep(backoff.toMillis());
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
        return Result.ok("");
    }

    @Override
    public @NonNull Result<String, MiddlewareError> extraSystemPrompt(
            @NonNull String runId,
            @NonNull List<Message> history,
            @NonNull Map<String, Object> context) {
        String instruction = state.instruction();
        if (instruction != null && !instruction.isBlank()) {
            return Result.ok("[Self-Healing]: " + instruction);
        }
        return Result.ok("");
    }
}
